# Generated by Django 4.1.2 on 2023-01-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField(verbose_name='Realease date')),
                ('cover', models.ImageField(upload_to='cover')),
                ('views', models.PositiveIntegerField()),
                ('autors', models.ManyToManyField(to='autor.autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_book', to='book.category')),
            ],
        ),
    ]
